import { Products } from 'src/app/models/product.model';
import { LoremIpsum } from 'lorem-ipsum';

const lorem = new LoremIpsum({
  sentencesPerParagraph: {
    max: 8,
    min: 4,
  },
  wordsPerSentence: {
    max: 16,
    min: 4,
  },
});

export const products: Products[] = [
  {
    product_id: 1,
    product_name: 'Reeder P13 Blue 32 GB 2021',
    product_image:
      'https://productimages.hepsiburada.net/s/115/280-413/110000063149613.jpg',
    description: 'Lenovo son model',
    comments: [
      {
        product_id: 1,
        comment_id: 1,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 1,
        comment_id: 2,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 1,
        comment_id: 3,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 1,
        comment_id: 4,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 1,
        comment_id: 5,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 1,
        comment_id: 6,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
    ],
    price: Math.floor(Math.random() * 5000) + 1,
    date: Date.now(),
    rating: {
      rate: 5,
      count: 222,
    },
  },
  {
    product_id: 2,
    product_name: 'Reeder P13 Blue Max',
    product_image:
      'https://productimages.hepsiburada.net/s/103/280-413/110000046592005.jpg',
    description: 'Lenovo son model',
    comments: [
      {
        product_id: 2,
        comment_id: 1,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 2,
        comment_id: 2,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 2,
        comment_id: 3,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 2,
        comment_id: 4,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 2,
        comment_id: 5,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 2,
        comment_id: 6,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
    ],
    price: Math.floor(Math.random() * 5000) + 1,
    date: Date.now(),
    rating: {
      rate: 4,
      count: 555,
    },
  },
  {
    product_id: 3,
    product_name: 'abc Lenovo V1VT',
    product_image:
      'https://productimages.hepsiburada.net/s/115/280-413/110000063149613.jpg',
    description: 'Lenovo son model',
    comments: [
      {
        product_id: 3,
        comment_id: 1,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 3,
        comment_id: 2,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 3,
        comment_id: 3,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 3,
        comment_id: 4,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 3,
        comment_id: 5,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 3,
        comment_id: 6,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
    ],
    price: Math.floor(Math.random() * 5000) + 1,
    date: Date.now(),
    rating: {
      rate: 2,
      count: 63,
    },
  },
  {
    product_id: 4,
    product_name: 'abc Lenovo V1VT',
    product_image:
      'https://productimages.hepsiburada.net/s/115/280-413/110000063149613.jpg',
    description: 'Lenovo son model',
    comments: [
      {
        product_id: 4,
        comment_id: 1,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 4,
        comment_id: 2,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 4,
        comment_id: 3,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 4,
        comment_id: 4,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 4,
        comment_id: 5,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 4,
        comment_id: 6,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
    ],
    price: Math.floor(Math.random() * 5000) + 1,
    date: Date.now(),
    rating: {
      rate: 2,
      count: 12,
    },
  },
  {
    product_id: 5,
    product_name: 'abc Lenovo V1VT',
    product_image:
      'https://productimages.hepsiburada.net/s/115/280-413/110000063149613.jpg',
    description: 'Lenovo son model',
    comments: [
      {
        product_id: 5,
        comment_id: 1,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 5,
        comment_id: 2,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 5,
        comment_id: 3,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 5,
        comment_id: 4,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 5,
        comment_id: 5,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 5,
        comment_id: 6,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
    ],
    price: Math.floor(Math.random() * 5000) + 1,
    date: 1555045662,
    rating: {
      rate: 4,
      count: 77,
    },
  },
  {
    product_id: 6,
    product_name: 'abc Lenovo V1VT',
    product_image:
      'https://productimages.hepsiburada.net/s/115/280-413/110000063149613.jpg',
    description: 'Lenovo son model',
    comments: [
      {
        product_id: 6,
        comment_id: 1,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 6,
        comment_id: 2,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 6,
        comment_id: 3,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 6,
        comment_id: 4,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 6,
        comment_id: 5,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 6,
        comment_id: 6,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
    ],
    price: Math.floor(Math.random() * 5000) + 1,
    date: Date.now(),
    rating: {
      rate: 1,
      count: 2,
    },
  },
  {
    product_id: 7,
    product_name: 'abc Lenovo V1VT',
    product_image:
      'https://productimages.hepsiburada.net/s/115/280-413/110000063149613.jpg',
    description: 'Lenovo son model',
    comments: [
      {
        product_id: 7,
        comment_id: 1,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 7,
        comment_id: 2,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 7,
        comment_id: 3,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 7,
        comment_id: 4,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 7,
        comment_id: 5,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 7,
        comment_id: 6,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
    ],
    price: Math.floor(Math.random() * 5000) + 1,
    date: Date.now(),
    rating: {
      rate: 2,
      count: 90,
    },
  },
  {
    product_id: 8,
    product_name: 'abc Lenovo V1VT',
    product_image:
      'https://productimages.hepsiburada.net/s/115/280-413/110000063149613.jpg',
    description: 'Lenovo son model',
    comments: [
      {
        product_id: 8,
        comment_id: 1,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 8,
        comment_id: 2,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 8,
        comment_id: 3,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 8,
        comment_id: 4,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 8,
        comment_id: 5,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 8,
        comment_id: 6,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
    ],
    price: Math.floor(Math.random() * 5000) + 1,
    date: Date.now(),
    rating: {
      rate: 2,
      count: 234,
    },
  },
  {
    product_id: 9,
    product_name: 'abc Lenovo V1VT',
    product_image:
      'https://productimages.hepsiburada.net/s/115/280-413/110000063149613.jpg',
    description: 'Lenovo son model',
    comments: [
      {
        product_id: 9,
        comment_id: 1,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 9,
        comment_id: 2,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 9,
        comment_id: 3,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 9,
        comment_id: 4,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 9,
        comment_id: 5,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 9,
        comment_id: 6,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
    ],
    price: Math.floor(Math.random() * 5000) + 1,
    date: Date.now(),
    rating: {
      rate: 3,
      count: 285,
    },
  },
  {
    product_id: 10,
    product_name: 'abc Lenovo V1VT',
    product_image:
      'https://productimages.hepsiburada.net/s/115/280-413/110000063149613.jpg',
    description: 'Lenovo son model',
    comments: [
      {
        product_id: 10,
        comment_id: 1,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 10,
        comment_id: 2,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 10,
        comment_id: 3,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 10,
        comment_id: 4,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 10,
        comment_id: 5,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 10,
        comment_id: 6,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
    ],
    price: Math.floor(Math.random() * 5000) + 1,
    date: Date.now(),
    rating: {
      rate: 5,
      count: 249,
    },
  },
  {
    product_id: 11,
    product_name: 'abc Lenovo V1VT',
    product_image:
      'https://productimages.hepsiburada.net/s/115/280-413/110000063149613.jpg',
    description: 'Lenovo son model',
    comments: [
      {
        product_id: 11,
        comment_id: 1,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 11,
        comment_id: 2,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 11,
        comment_id: 3,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 11,
        comment_id: 4,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 11,
        comment_id: 5,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 11,
        comment_id: 6,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
    ],
    price: Math.floor(Math.random() * 5000) + 1,
    date: Date.now(),
    rating: {
      rate: 4,
      count: 121,
    },
  },
  {
    product_id: 12,
    product_name: 'abc Lenovo V1VT',
    product_image:
      'https://productimages.hepsiburada.net/s/115/280-413/110000063149613.jpg',
    description: 'Lenovo son model',
    comments: [
      {
        product_id: 12,
        comment_id: 1,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 12,
        comment_id: 2,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 12,
        comment_id: 3,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 12,
        comment_id: 4,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 12,
        comment_id: 5,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
      {
        product_id: 12,
        comment_id: 6,
        userName: 'Erkin',
        comment: lorem.generateSentences(5),
        rating: Math.floor(Math.random() * 5) + 1,
      },
    ],
    price: Math.floor(Math.random() * 5000) + 1,
    date: Date.now() + Math.floor(Math.random() * 4) + 1,
    rating: {
      rate: 3,
      count: 100,
    },
  },
];
